# Site settings
title: Deheng.Qian
description: 'hello world' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nanxiangshui.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/MVM-logo-full.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Deheng Qian # add your name
author-pic: myfamily.jpg
about-author: I was born in 1989 in Fenyi county, Jiangxi province, China. I received a bachelor's degree in Computer Science and Technology from the Huazhong University of Science and Technology in 2011. Then I obtained my Ph.D. degree from the Chinese Academy of Sciences in 2016. I got married to Mengling Yan in 2018. Our son, named Chengyi Qian, was born in 2021. This is a photo of my wife and my son.

# Contact links
email: 835853273@qq.com # Add your Email address
phone: (+86) 18810461380 # Add your Phone number
website: https://nanxiangshui.github.io # Add your website

# Tracker
analytics: -KuuLsQAAAAJ&hl

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]